apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aml-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alukiko/mlops-aml-transactions.git
    targetRevision: argocd-demo
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: aml-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
