resources:
  - namespace.yaml
  - storage.yaml
  - configmap.yaml
  - secret.yaml
  - backend.yaml
  - frontend.yaml
  - mlflow.yaml
  - prometheus-grafana.yaml
  - drift-cronjob.yaml
  - mlflow-db-upgrade-job.yaml

configMapGenerator:
  - name: grafana-dashboard
    namespace: aml-monitoring
    files:
      - aml-monitoring.json=grafana/aml-monitoring.json

generatorOptions:
  disableNameSuffixHash: true
