apiVersion: batch/v1
kind: Job
metadata:
  name: aml-retraining-manual
  namespace: aml-monitoring
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: retrain
          image: ghcr.io/alukiko/mlops-aml-transactions/aml-backend:d108a76e83e8eb269a77c13c6f072b70139491f8
          command: ["python", "-m", "aml_monitoring.cli", "retrain"]
          envFrom:
            - configMapRef:
                name: aml-config
            - secretRef:
                name: aml-secrets
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: runtime
              mountPath: /app/runtime
              subPath: runtime
            - name: runtime
              mountPath: /app/mlartifacts
              subPath: mlartifacts
            - name: runtime
              mountPath: /app/models
              subPath: models
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: aml-data-pvc
        - name: runtime
          persistentVolumeClaim:
            claimName: aml-runtime-pvc
  backoffLimit: 1
