apiVersion: v1
kind: Secret
metadata:
  name: aml-secrets
  namespace: aml-monitoring
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: replace-me
  AWS_SECRET_ACCESS_KEY: replace-me
  registry_username: replace-me
  registry_password: replace-me
